# Generated by Django 3.0.6 on 2020-05-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nit',
            field=models.IntegerField(unique=True),
        ),
    ]
